version: "4.28"
services:
  php-apache-environment:
    container_name: php-food-app
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./app/src:/var/www/html
    ports:
      - "8080:80"
  db:
    container_name: php-food-app-db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: php-food-app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    restart: always
    environment:
      PMA_HOST: php-food-app-db
    depends_on:
      - db